name: expense_tracker_app
description: A professional expense tracker showcasing Flutter development skills
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Date & Time
  intl: ^0.18.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # File Operations & Export
  pdf: ^3.10.7
  printing: ^5.11.1
  csv: ^5.0.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  # Authentication
  local_auth: ^2.1.6
  crypto: ^3.0.3
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Animations
  lottie: ^2.7.0
  
  # Currency & Formatting
  currency_picker: ^2.0.16
  
  # Backup & Cloud (Optional) - Removed Firebase for now
  
  # Image Handling
  image_picker: ^1.0.4
  
  # HTTP Requests
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
